In [1]:
import pandas as pd

import refinitiv.data as rd
rd.open_session()

In [2]:
old_spx = pd.read_pickle("./spx-past-5-years/spx_past_5_years")
old_spx_index = pd.read_pickle("./spx-past-5-years/spx_index_past_5_years")

In [3]:
old_spx.head()

Price Close,POOL.OQ,CHRW.OQ,AJG.N,CNP.N,AMCR.N,WM.N,BA.N,FOX.OQ,WY.N,MCD.N,...,NRG.N,MKTX.OQ,APO.N,LMT.N,DLR.N,PSX.N,SCHW.N,SNPS.OQ,J.N,AVY.N
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-30,223.97,72.64,100.2,26.67,10.83,122.76,323.3,36.46,27.752942,216.18,...,37.16,358.16,46.63,435.9,125.74,96.41,47.19,150.82,78.89452,136.11
2020-01-31,219.3,72.22,102.57,26.48,10.59,121.7,318.27,36.33,26.719244,213.97,...,36.89,354.18,47.32,428.12,122.99,91.37,45.55,147.51,77.258016,131.24
2020-02-03,220.92,72.01,104.26,26.34,10.68,122.69,316.0,36.83,26.045494,215.18,...,37.54,355.5,45.94,423.86,123.14,88.97,45.68,150.26,77.683841,133.98
2020-02-04,222.85,72.23,104.7,26.52,10.87,122.86,317.94,37.4,26.008576,214.62,...,37.26,355.0,47.06,430.78,124.99,88.72,47.08,155.81,79.704422,136.85
2020-02-05,223.82,72.74,105.08,26.75,11.02,123.61,329.55,37.93,26.691555,214.37,...,38.0,341.85,47.96,435.19,123.86,92.64,48.29,154.21,80.781509,140.11

In [4]:
import datetime

#start_date = str(old_spx.index[-1]).split(" ")[0]
#start_date = str(old_spx.index[-1].to_pydatetime().timedelta(days=1)).split(" ")[0]

start_date = str(old_spx.index[-1].to_pydatetime() + datetime.timedelta(days=1)).split(" ")[0]
end_date = str(datetime.date.today() - datetime.timedelta(days=1))
start_date, end_date

('2025-01-30', '2025-04-08')

In [5]:
new_spx = rd.get_history(
    universe=["0#.SPX"],
    fields=["TR.PriceClose"],
    interval="1D",
    start=start_date,
    end=end_date,
)

new_spx_index = rd.get_history(
    universe=[".SPX"],
    fields=["TR.PriceClose"],
    interval="1D",
    start=start_date,
    end=end_date,
)

column_names = list(new_spx_index.columns)
new_spx_index = new_spx_index.rename(columns={column_names[0]: "SPX"})
new_spx_index.columns.name = "Price Close"

new_spx.head()

Price Close,POOL.OQ,CHRW.OQ,AJG.N,CNP.N,AMCR.N,WM.N,BA.N,FOX.OQ,TKO.N,WY.N,...,NRG.N,MKTX.OQ,APO.N,LMT.N,DLR.N,PSX.N,SCHW.N,SNPS.OQ,J.N,AVY.N
Date,,,,,,,,,,,,,,,,,,,,,
2025-01-30,348.62,100.44,299.03,32.88,9.75,222.43,179.53,48.37,157.47,30.96,...,105.0,217.77,171.76,459.65,164.23,120.84,83.6,526.36,139.82,182.49
2025-01-31,344.25,99.49,301.82,32.57,9.72,220.26,176.52,48.6,155.21,30.62,...,102.44,220.63,170.98,462.95,163.86,117.87,82.72,525.48,140.13,185.73
2025-02-03,337.5,98.1,309.0,32.51,9.56,223.72,175.87,49.19,157.05,30.75,...,102.68,218.19,167.12,455.42,161.43,117.86,82.75,520.25,138.78,183.34
2025-02-04,339.35,98.83,312.21,32.15,10.05,222.14,176.23,51.55,157.74,30.14,...,101.66,217.31,162.59,453.68,163.34,123.61,81.8,523.88,133.99,182.62
2025-02-05,339.2,97.25,316.3,32.27,10.22,224.77,181.84,51.27,161.02,30.34,...,102.88,198.07,165.75,449.87,167.19,123.32,81.87,528.42,132.27,184.63

In [6]:
spx_index_df = pd.concat((old_spx_index, new_spx_index), axis=0)
spx_index_df.head()

spx_df = pd.concat((old_spx, new_spx), axis=0)
spx_df

Price Close,POOL.OQ,CHRW.OQ,AJG.N,CNP.N,AMCR.N,WM.N,BA.N,FOX.OQ,WY.N,MCD.N,...,DLR.N,PSX.N,SCHW.N,SNPS.OQ,J.N,AVY.N,TKO.N,WSM.N,EXE.OQ,DASH.OQ
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-30,223.97,72.64,100.2,26.67,10.83,122.76,323.3,36.46,27.752942,216.18,...,125.74,96.41,47.19,150.82,78.89452,136.11,<NA>,<NA>,<NA>,<NA>
2020-01-31,219.3,72.22,102.57,26.48,10.59,121.7,318.27,36.33,26.719244,213.97,...,122.99,91.37,45.55,147.51,77.258016,131.24,<NA>,<NA>,<NA>,<NA>
2020-02-03,220.92,72.01,104.26,26.34,10.68,122.69,316.0,36.83,26.045494,215.18,...,123.14,88.97,45.68,150.26,77.683841,133.98,<NA>,<NA>,<NA>,<NA>
2020-02-04,222.85,72.23,104.7,26.52,10.87,122.86,317.94,37.4,26.008576,214.62,...,124.99,88.72,47.08,155.81,79.704422,136.85,<NA>,<NA>,<NA>,<NA>
2020-02-05,223.82,72.74,105.08,26.75,11.02,123.61,329.55,37.93,26.691555,214.37,...,123.86,92.64,48.29,154.21,80.781509,140.11,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-02,325.66,102.82,344.07,36.93,9.8,234.56,168.56,53.0,29.48,311.58,...,148.68,124.06,78.59,438.55,124.52,180.58,158.58,165.01,113.87,189.25
2025-04-03,313.85,94.77,344.4,37.36,9.57,236.83,150.91,47.9,27.43,318.27,...,141.09,107.18,74.87,417.76,118.48,176.34,150.44,138.86,110.55,173.99
2025-04-04,315.05,90.94,319.25,36.08,9.22,225.2,136.59,45.73,26.26,300.11,...,137.5,98.81,69.06,388.13,111.45,170.25,139.58,141.68,100.01,163.16
2025-04-07,303.08,89.17,310.86,35.5,8.92,220.56,138.86,44.53,25.48,299.89,...,136.67,96.59,70.04,380.9,111.06,166.28,141.18,145.09,100.06,166.3
2025-04-08,290.96,86.965,311.53,35.55,8.57,216.47,139.39,43.81,24.82,299.83,...,136.11,92.87,69.93,381.59,110.79,159.58,138.96,139.21,100.01,165.75

In [7]:
spx_df.to_pickle(f"spx_df_{end_date}")
spx_index_df.to_pickle(f"spx_index_df_{end_date}")